# Generated by Django 4.2.6 on 2023-10-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='давление'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='wind_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='скорость ветра'),
        ),
    ]
